local skills = {}

skills.weapon = {
    [1] = {id=1,en="Combo",skillchain={"Impaction"}},
    [2] = {id=2,en="Shoulder Tackle",skillchain={"Reverberation","Impaction"}},
    [3] = {id=3,en="One Inch Punch",skillchain={"Compression"}},
    [4] = {id=4,en="Backhand Blow",skillchain={"Detonation"}},
    [5] = {id=5,en="Raging Fists",skillchain={"Impaction"}},
    [6] = {id=6,en="Spinning Attack",skillchain={"Liquefaction","Impaction"}},
    [7] = {id=7,en="Howling Fist",skillchain={"Transfixion","Impaction"}},
    [8] = {id=8,en="Dragon Kick",skillchain={"Fragmentation"}},
    [9] = {id=9,en="Asuran Fists",skillchain={"Gravitation","Liquefaction"}},
    [10] = {id=10,en="Final Heaven",skillchain={"Light","Fusion"}},
    [11] = {id=11,en="Ascetic's Fury",skillchain={"Fusion","Transfixion"}},
    [12] = {id=12,en="Stringing Pummel",skillchain={"Gravitation","Liquefaction"}},
    [13] = {id=13,en="Tornado Kick",skillchain={"Induration","Detonation","Impaction"}},
    [14] = {id=14,en="Victory Smite",skillchain={"Light","Fragmentation"}},
    [15] = {id=15,en="Shijin Spiral",skillchain={"Fusion","Reverberation"},aeonic="Light",weapon=20515},
    [16] = {id=16,en="Wasp Sting",skillchain={"Scission"}},
    [17] = {id=17,en="Viper Bite",skillchain={"Scission"}},
    [18] = {id=18,en="Shadowstitch",skillchain={"Reverberation"}},
    [19] = {id=19,en="Gust Slash",skillchain={"Detonation"}},
    [20] = {id=20,en="Cyclone",skillchain={"Detonation","Impaction"}},
    [23] = {id=23,en="Dancing Edge",skillchain={"Scission","Detonation"}},
    [24] = {id=24,en="Shark Bite",skillchain={"Fragmentation"}},
    [25] = {id=25,en="Evisceration",skillchain={"Gravitation","Transfixion"}},
    [26] = {id=26,en="Mercy Stroke",skillchain={"Darkness","Gravitation"}},
    [27] = {id=27,en="Mandalic Stab",skillchain={"Fusion","Compression"}},
    [28] = {id=28,en="Mordant Rime",skillchain={"Fragmentation","Distortion"}},
    [29] = {id=29,en="Pyrrhic Kleos",skillchain={"Distortion","Scission"}},
    [30] = {id=30,en="Aeolian Edge",skillchain={"Scission","Detonation","Impaction"}},
    [31] = {id=31,en="Rudra's Storm",skillchain={"Darkness","Distortion"}},
    [32] = {id=32,en="Fast Blade",skillchain={"Scission"}},
    [33] = {id=33,en="Burning Blade",skillchain={"Liquefaction"}},
    [34] = {id=34,en="Red Lotus Blade",skillchain={"Liquefaction","Detonation"}},
    [35] = {id=35,en="Flat Blade",skillchain={"Impaction"}},
    [36] = {id=36,en="Shining Blade",skillchain={"Scission"}},
    [37] = {id=37,en="Seraph Blade",skillchain={"Scission"}},
    [38] = {id=38,en="Circle Blade",skillchain={"Reverberation","Impaction"}},
    [40] = {id=40,en="Vorpal Blade",skillchain={"Scission","Impaction"}},
    [41] = {id=41,en="Swift Blade",skillchain={"Gravitation"}},
    [42] = {id=42,en="Savage Blade",skillchain={"Fragmentation","Scission"}},
    [43] = {id=43,en="Knights of Round",skillchain={"Light","Fusion"}},
    [44] = {id=44,en="Death Blossom",skillchain={"Fragmentation","Distortion"}},
    [45] = {id=45,en="Atonement",skillchain={"Fusion","Reverberation"}},
    [46] = {id=46,en="Expiacion",skillchain={"Distortion","Scission"}},
    [48] = {id=48,en="Hard Slash",skillchain={"Scission"}},
    [49] = {id=49,en="Power Slash",skillchain={"Transfixion"}},
    [50] = {id=50,en="Frostbite",skillchain={"Induration"}},
    [51] = {id=51,en="Freezebite",skillchain={"Induration","Detonation"}},
    [52] = {id=52,en="Shockwave",skillchain={"Reverberation"}},
    [53] = {id=53,en="Crescent Moon",skillchain={"Scission"}},
    [54] = {id=54,en="Sickle Moon",skillchain={"Scission","Impaction"}},
    [55] = {id=55,en="Spinning Slash",skillchain={"Fragmentation"}},
    [56] = {id=56,en="Ground Strike",skillchain={"Fragmentation","Distortion"}},
    [57] = {id=57,en="Scourge",skillchain={"Light","Fusion"}},
    [58] = {id=58,en="Herculean Slash",skillchain={"Induration","Detonation","Impaction"}},
    [59] = {id=59,en="Torcleaver",skillchain={"Light","Distortion"}},
    [60] = {id=60,en="Resolution",skillchain={"Fragmentation","Scission"},aeonic="Light",weapon=21694},
    [61] = {id=61,en="Dimidiation",skillchain={"Light","Fragmentation"}},
    [64] = {id=64,en="Raging Axe",skillchain={"Detonation","Impaction"}},
    [65] = {id=65,en="Smash Axe",skillchain={"Induration","Reverberation"}},
    [66] = {id=66,en="Gale Axe",skillchain={"Detonation"}},
    [67] = {id=67,en="Avalanche Axe",skillchain={"Scission","Impaction"}},
    [68] = {id=68,en="Spinning Axe",skillchain={"Liquefaction","Scission","Impaction"}},
    [69] = {id=69,en="Rampage",skillchain={"Scission"}},
    [70] = {id=70,en="Calamity",skillchain={"Scission","Impaction"}},
    [71] = {id=71,en="Mistral Axe",skillchain={"Fusion"}},
    [72] = {id=72,en="Decimation",skillchain={"Fusion","Reverberation"}},
    [73] = {id=73,en="Onslaught",skillchain={"Darkness","Gravitation"}},
    [74] = {id=74,en="Primal Rend",skillchain={"Gravitation","Reverberation"}},
    [75] = {id=75,en="Bora Axe",skillchain={"Scission","Detonation"}},
    [76] = {id=76,en="Cloudsplitter",skillchain={"Darkness","Fragmentation"}},
    [77] = {id=77,en="Ruinator",skillchain={"Distortion","Detonation"},aeonic="Darkness",weapon=21753},
    [80] = {id=80,en="Shield Break",skillchain={"Impaction"}},
    [81] = {id=81,en="Iron Tempest",skillchain={"Scission"}},
    [82] = {id=82,en="Sturmwind",skillchain={"Reverberation","Scission"}},
    [83] = {id=83,en="Armor Break",skillchain={"Impaction"}},
    [84] = {id=84,en="Keen Edge",skillchain={"Compression"}},
    [85] = {id=85,en="Weapon Break",skillchain={"Impaction"}},
    [86] = {id=86,en="Raging Rush",skillchain={"Induration","Reverberation"}},
    [87] = {id=87,en="Full Break",skillchain={"Distortion"}},
    [88] = {id=88,en="Steel Cyclone",skillchain={"Distortion","Detonation"}},
    [89] = {id=89,en="Metatron Torment",skillchain={"Light","Fusion"}},
    [90] = {id=90,en="King's Justice",skillchain={"Fragmentation","Scission"}},
    [91] = {id=91,en="Fell Cleave",skillchain={"Scission","Detonation","Impaction"}},
    [92] = {id=92,en="Ukko's Fury",skillchain={"Light","Fragmentation"}},
    [93] = {id=93,en="Upheaval",skillchain={"Fusion","Compression"},aeonic="Light",weapon=20843},
    [96] = {id=96,en="Slice",skillchain={"Scission"}},
    [97] = {id=97,en="Dark Harvest",skillchain={"Reverberation"}},
    [98] = {id=98,en="Shadow of Death",skillchain={"Induration","Reverberation"}},
    [99] = {id=99,en="Nightmare Scythe",skillchain={"Compression","Scission"}},
    [100] = {id=100,en="Spinning Scythe",skillchain={"Reverberation","Scission"}},
    [101] = {id=101,en="Vorpal Scythe",skillchain={"Transfixion","Scission"}},
    [102] = {id=102,en="Guillotine",skillchain={"Induration"}},
    [103] = {id=103,en="Cross Reaper",skillchain={"Distortion"}},
    [104] = {id=104,en="Spiral Hell",skillchain={"Distortion","Scission"}},
    [105] = {id=105,en="Catastrophe",skillchain={"Darkness","Gravitation"}},
    [106] = {id=106,en="Insurgency",skillchain={"Fusion","Compression"}},
    [107] = {id=107,en="Infernal Scythe",skillchain={"Compression","Reverberation"}},
    [108] = {id=108,en="Quietus",skillchain={"Darkness","Distortion"}},
    [109] = {id=109,en="Entropy",skillchain={"Gravitation","Reverberation"},aeonic="Darkness",weapon=20890},
    [112] = {id=112,en="Double Thrust",skillchain={"Transfixion"}},
    [113] = {id=113,en="Thunder Thrust",skillchain={"Transfixion","Impaction"}},
    [114] = {id=114,en="Raiden Thrust",skillchain={"Transfixion","Impaction"}},
    [115] = {id=115,en="Leg Sweep",skillchain={"Impaction"}},
    [116] = {id=116,en="Penta Thrust",skillchain={"Compression"}},
    [117] = {id=117,en="Vorpal Thrust",skillchain={"Reverberation","Transfixion"}},
    [118] = {id=118,en="Skewer",skillchain={"Transfixion","Impaction"}},
    [119] = {id=119,en="Wheeling Thrust",skillchain={"Fusion"}},
    [120] = {id=120,en="Impulse Drive",skillchain={"Gravitation","Induration"}},
    [121] = {id=121,en="Geirskogul",skillchain={"Light","Distortion"}},
    [122] = {id=122,en="Drakesbane",skillchain={"Fusion","Transfixion"}},
    [123] = {id=123,en="Sonic Thrust",skillchain={"Transfixion","Scission"}},
    [124] = {id=124,en="Camlann's Torment",skillchain={"Light","Fragmentation"}},
    [125] = {id=125,en="Stardiver",skillchain={"Gravitation","Transfixion"},aeonic="Darkness",weapon=20935},
    [128] = {id=128,en="Blade: Rin",skillchain={"Transfixion"}},
    [129] = {id=129,en="Blade: Retsu",skillchain={"Scission"}},
    [130] = {id=130,en="Blade: Teki",skillchain={"Reverberation"}},
    [131] = {id=131,en="Blade: To",skillchain={"Induration","Detonation"}},
    [132] = {id=132,en="Blade: Chi",skillchain={"Transfixion","Impaction"}},
    [133] = {id=133,en="Blade: Ei",skillchain={"Compression"}},
    [134] = {id=134,en="Blade: Jin",skillchain={"Detonation","Impaction"}},
    [135] = {id=135,en="Blade: Ten",skillchain={"Gravitation"}},
    [136] = {id=136,en="Blade: Ku",skillchain={"Gravitation","Transfixion"}},
    [137] = {id=137,en="Blade: Metsu",skillchain={"Darkness","Fragmentation"}},
    [138] = {id=138,en="Blade: Kamu",skillchain={"Fragmentation","Compression"}},
    [139] = {id=139,en="Blade: Yu",skillchain={"Reverberation","Scission"}},
    [140] = {id=140,en="Blade: Hi",skillchain={"Darkness","Gravitation"}},
    [141] = {id=141,en="Blade: Shun",skillchain={"Fusion","Impaction"},aeonic="Light",weapon=20977},
    [144] = {id=144,en="Tachi: Enpi",skillchain={"Transfixion","Scission"}},
    [145] = {id=145,en="Tachi: Hobaku",skillchain={"Induration"}},
    [146] = {id=146,en="Tachi: Goten",skillchain={"Transfixion","Impaction"}},
    [147] = {id=147,en="Tachi: Kagero",skillchain={"Liquefaction"}},
    [148] = {id=148,en="Tachi: Jinpu",skillchain={"Scission","Detonation"}},
    [149] = {id=149,en="Tachi: Koki",skillchain={"Reverberation","Impaction"}},
    [150] = {id=150,en="Tachi: Yukikaze",skillchain={"Induration","Detonation"}},
    [151] = {id=151,en="Tachi: Gekko",skillchain={"Distortion","Reverberation"}},
    [152] = {id=152,en="Tachi: Kasha",skillchain={"Fusion","Compression"}},
    [153] = {id=153,en="Tachi: Kaiten",skillchain={"Light","Fragmentation"}},
    [154] = {id=154,en="Tachi: Rana",skillchain={"Gravitation","Induration"}},
    [155] = {id=155,en="Tachi: Ageha",skillchain={"Compression","Scission"}},
    [156] = {id=156,en="Tachi: Fudo",skillchain={"Light","Distortion"}},
    [157] = {id=157,en="Tachi: Shoha",skillchain={"Fragmentation","Compression"},aeonic="Light",weapon=21025},
    [160] = {id=160,en="Shining Strike",skillchain={"Impaction"}},
    [161] = {id=161,en="Seraph Strike",skillchain={"Impaction"}},
    [162] = {id=162,en="Brainshaker",skillchain={"Reverberation"}},
    [165] = {id=165,en="Skullbreaker",skillchain={"Induration","Reverberation"}},
    [166] = {id=166,en="True Strike",skillchain={"Detonation","Impaction"}},
    [167] = {id=167,en="Judgment",skillchain={"Impaction"}},
    [168] = {id=168,en="Hexa Strike",skillchain={"Fusion"}},
    [169] = {id=169,en="Black Halo",skillchain={"Fragmentation","Compression"}},
    [170] = {id=170,en="Randgrith",skillchain={"Light","Fragmentation"}},
    [172] = {id=172,en="Flash Nova",skillchain={"Induration","Reverberation"}},
    [174] = {id=174,en="Realmrazer",skillchain={"Fusion","Impaction"},aeonic="Light",weapon=21082},
    [175] = {id=175,en="Exudation",skillchain={"Darkness","Fragmentation"}},
    [176] = {id=176,en="Heavy Swing",skillchain={"Impaction"}},
    [177] = {id=177,en="Rock Crusher",skillchain={"Impaction"}},
    [178] = {id=178,en="Earth Crusher",skillchain={"Detonation","Impaction"}},
    [179] = {id=179,en="Starburst",skillchain={"Compression","Reverberation"}},
    [180] = {id=180,en="Sunburst",skillchain={"Compression","Reverberation"}},
    [181] = {id=181,en="Shell Crusher",skillchain={"Detonation"}},
    [182] = {id=182,en="Full Swing",skillchain={"Liquefaction","Impaction"}},
    [184] = {id=184,en="Retribution",skillchain={"Gravitation","Reverberation"}},
    [185] = {id=185,en="Gate of Tartarus",skillchain={"Darkness","Distortion"}},
    [186] = {id=186,en="Vidohunir",skillchain={"Fragmentation","Distortion"}},
    [187] = {id=187,en="Garland of Bliss",skillchain={"Fusion","Reverberation"}},
    [188] = {id=188,en="Omniscience",skillchain={"Gravitation","Transfixion"}},
    [189] = {id=189,en="Cataclysm",skillchain={"Compression","Reverberation"}},
    [191] = {id=191,en="Shattersoul",skillchain={"Gravitation","Induration"},aeonic="Darkness",weapon=21147},
    [192] = {id=192,en="Flaming Arrow",skillchain={"Liquefaction","Transfixion"}},
    [193] = {id=193,en="Piercing Arrow",skillchain={"Reverberation","Transfixion"}},
    [194] = {id=194,en="Dulling Arrow",skillchain={"Liquefaction","Transfixion"}},
    [196] = {id=196,en="Sidewinder",skillchain={"Reverberation","Transfixion","Detonation"}},
    [197] = {id=197,en="Blast Arrow",skillchain={"Induration","Transfixion"}},
    [198] = {id=198,en="Arching Arrow",skillchain={"Fusion"}},
    [199] = {id=199,en="Empyreal Arrow",skillchain={"Fusion","Transfixion"}},
    [200] = {id=200,en="Namas Arrow",skillchain={"Light","Distortion"}},
    [201] = {id=201,en="Refulgent Arrow",skillchain={"Reverberation","Transfixion"}},
    [202] = {id=202,en="Jishnu's Radiance",skillchain={"Light","Fusion"}},
    [203] = {id=203,en="Apex Arrow",skillchain={"Fragmentation","Transfixion"},aeonic="Light",weapon=22117},
    [208] = {id=208,en="Hot Shot",skillchain={"Liquefaction","Transfixion"}},
    [209] = {id=209,en="Split Shot",skillchain={"Reverberation","Transfixion"}},
    [210] = {id=210,en="Sniper Shot",skillchain={"Liquefaction","Transfixion"}},
    [212] = {id=212,en="Slug Shot",skillchain={"Reverberation","Transfixion","Detonation"}},
    [213] = {id=213,en="Blast Shot",skillchain={"Induration","Transfixion"}},
    [214] = {id=214,en="Heavy Shot",skillchain={"Fusion"}},
    [215] = {id=215,en="Detonator",skillchain={"Fusion","Transfixion"}},
    [216] = {id=216,en="Coronach",skillchain={"Darkness","Fragmentation"}},
    [217] = {id=217,en="Trueflight",skillchain={"Fragmentation","Scission"}},
    [218] = {id=218,en="Leaden Salute",skillchain={"Gravitation","Transfixion"}},
    [219] = {id=219,en="Numbing Shot",skillchain={"Induration","Detonation","Impaction"}},
    [220] = {id=220,en="Wildfire",skillchain={"Darkness","Gravitation"}},
    [221] = {id=221,en="Last Stand",skillchain={"Fusion","Reverberation"},aeonic="Light",weapon=21485},
    [224] = {id=224,en="Exenterator",skillchain={"Fragmentation","Scission"},aeonic="Light",weapon=20594},
    [225] = {id=225,en="Chant du Cygne",skillchain={"Light","Distortion"}},
    [226] = {id=226,en="Requiescat",skillchain={"Gravitation","Scission"},aeonic="Darkness",weapon=20695},
    [227] = {id=227,en="Knights of Rotund",skillchain={"Light"}},
    [238] = {id=238,en="Uriel Blade",skillchain={"Light","Fragmentation"}},
    [239] = {id=239,en="Glory Slash",skillchain={"Light","Fusion"}},
    }

skills.abilities = {
    [513] = {id=513,en="Poison Nails",skillchain={"Transfixion"}},
    [521] = {id=521,en="Regal Scratch",skillchain={"Scission"}},
    [528] = {id=528,en="Moonlit Charge",skillchain={"Compression"}},
    [529] = {id=529,en="Crescent Fang",skillchain={"Transfixion"}},
    [534] = {id=534,en="Eclipse Bite",skillchain={"Gravitation","Scission"}},
    [544] = {id=544,en="Punch",skillchain={"Liquefaction"}},
    [546] = {id=546,en="Burning Strike",skillchain={"Impaction"}},
    [547] = {id=547,en="Double Punch",skillchain={"Compression"}},
    [550] = {id=550,en="Flaming Crush",skillchain={"Fusion","Reverberation"}},
    [560] = {id=560,en="Rock Throw",skillchain={"Scission"}},
    [562] = {id=562,en="Rock Buster",skillchain={"Reverberation"}},
    [563] = {id=563,en="Megalith Throw",skillchain={"Induration"}},
    [566] = {id=566,en="Mountain Buster",skillchain={"Gravitation","Induration"}},
    [570] = {id=570,en="Crag Throw",skillchain={"Gravitation","Scission"}},
    [576] = {id=576,en="Barracuda Dive",skillchain={"Reverberation"}},
    [578] = {id=578,en="Tail Whip",skillchain={"Detonation"}},
    [582] = {id=582,en="Spinning Dive",skillchain={"Distortion","Detonation"}},
    [592] = {id=592,en="Claw",skillchain={"Detonation"}},
    [598] = {id=598,en="Predator Claws",skillchain={"Fragmentation","Scission"}},
    [608] = {id=608,en="Axe Kick",skillchain={"Induration"}},
    [612] = {id=612,en="Double Slap",skillchain={"Scission"}},
    [614] = {id=614,en="Rush",skillchain={"Distortion","Scission"}},
    [624] = {id=624,en="Shock Strike",skillchain={"Impaction"}},
    [630] = {id=630,en="Chaotic Strike",skillchain={"Fragmentation","Transfixion"}},
    [634] = {id=634,en="Volt Strike",skillchain={"Fragmentation","Scission"}},
    [656] = {id=656,en="Camisado",skillchain={"Compression"}},
    [667] = {id=667,en="Blindside",skillchain={"Gravitation","Transfixion"}},
    [672] = {id=672,en="Foot Kick",skillchain={"Reverberation"}},
    [674] = {id=674,en="Whirl Claws",skillchain={"Impaction"}},
    [675] = {id=675,en="Head Butt",skillchain={"Detonation"}},
    [677] = {id=677,en="Wild Oats",skillchain={"Transfixion"}},
    [678] = {id=678,en="Leaf Dagger",skillchain={"Scission"}},
    [681] = {id=681,en="Razor Fang",skillchain={"Impaction"}},
    [682] = {id=682,en="Claw Cyclone",skillchain={"Scission"}},
    [683] = {id=683,en="Tail Blow",skillchain={"Impaction"}},
    [685] = {id=685,en="Blockhead",skillchain={"Reverberation"}},
    [686] = {id=686,en="Brain Crush",skillchain={"Liquefaction"}},
    [689] = {id=689,en="Lamb Chop",skillchain={"Impaction"}},
    [691] = {id=691,en="Sheep Charge",skillchain={"Reverberation"}},
    [695] = {id=695,en="Big Scissors",skillchain={"Scission"}},
    [698] = {id=698,en="Needleshot",skillchain={"Transfixion"}},
    [699] = {id=699,en="??? Needles",skillchain={"Darkness","Fragmentation"}},
    [700] = {id=700,en="Frogkick",skillchain={"Compression"}},
    [707] = {id=707,en="Power Attack",skillchain={"Reverberation"}},
    [709] = {id=709,en="Rhino Attack",skillchain={"Detonation"}},
    [717] = {id=717,en="Mandibular Bite",skillchain={"Detonation"}},
    [723] = {id=723,en="Nimble Snap",skillchain={"Impaction"}},
    [724] = {id=724,en="Cyclotail",skillchain={"Impaction"}},
    [726] = {id=726,en="Double Claw",skillchain={"Liquefaction"}},
    [727] = {id=727,en="Grapple",skillchain={"Reverberation"}},
    [728] = {id=728,en="Spinning Top",skillchain={"Impaction"}},
    [732] = {id=732,en="Suction",skillchain={"Compression"}},
    [736] = {id=736,en="Sudden Lunge",skillchain={"Impaction"}},
    [737] = {id=737,en="Spiral Spin",skillchain={"Scission"}},
    [743] = {id=743,en="Scythe Tail",skillchain={"Liquefaction"}},
    [744] = {id=744,en="Ripper Fang",skillchain={"Induration"}},
    [745] = {id=745,en="Chomp Rush",skillchain={"Darkness","Gravitation"}},
    [749] = {id=749,en="Back Heel",skillchain={"Reverberation"}},
    [753] = {id=753,en="Tortoise Stomp",skillchain={"Liquefaction"}},
    [756] = {id=756,en="Wing Slap",skillchain={"Gravitation","Liquefaction"}},
    [757] = {id=757,en="Beak Lunge",skillchain={"Scission"}},
    [759] = {id=759,en="Recoil Dive",skillchain={"Transfixion"}},
    [761] = {id=761,en="Sensilla Blades",skillchain={"Scission"}},
    [762] = {id=762,en="Tegmina Buffet",skillchain={"Distortion","Detonation"}},
    [764] = {id=764,en="Swooping Frenzy",skillchain={"Fusion","Reverberation"}},
    [765] = {id=765,en="Sweeping Gouge",skillchain={"Induration"}},
    [767] = {id=767,en="Pentapeck",skillchain={"Light","Distortion"}},
    [768] = {id=768,en="Tickling Tendrils",skillchain={"Impaction"}},
    [772] = {id=772,en="Somersault",skillchain={"Compression"}},
    [776] = {id=776,en="Pecking Flurry",skillchain={"Transfixion"}},
    [777] = {id=777,en="Sickle Slash",skillchain={"Transfixion"}},
    [780] = {id=780,en="Regal Gash",skillchain={"Distortion","Detonation"}},
    }

skills.blu = {
    [519] = {id=519,en="Screwdriver",skillchain={"Transfixion","Scission"}},
    [527] = {id=527,en="Smite of Rage",skillchain={"Detonation"}},
    [529] = {id=529,en="Bludgeon",skillchain={"Liquefaction"}},
    [539] = {id=539,en="Terror Touch",skillchain={"Compression","Reverberation"}},
    [540] = {id=540,en="Spinal Cleave",skillchain={"Scission","Detonation"}},
    [543] = {id=543,en="Mandibular Bite",skillchain={"Induration"}},
    [545] = {id=545,en="Sickle Slash",skillchain={"Compression"}},
    [551] = {id=551,en="Power Attack",skillchain={"Reverberation"}},
    [554] = {id=554,en="Death Scissors",skillchain={"Compression","Reverberation"}},
    [560] = {id=560,en="Frenetic Rip",skillchain={"Induration"}},
    [564] = {id=564,en="Body Slam",skillchain={"Impaction"}},
    [567] = {id=567,en="Helldive",skillchain={"Transfixion"}},
    [569] = {id=569,en="Jet Stream",skillchain={"Impaction"}},
    [577] = {id=577,en="Foot Kick",skillchain={"Detonation"}},
    [585] = {id=585,en="Ram Charge",skillchain={"Fragmentation"}},
    [587] = {id=587,en="Claw Cyclone",skillchain={"Scission"}},
    [589] = {id=589,en="Dimensional Death",skillchain={"Transfixion","Impaction"}},
    [594] = {id=594,en="Uppercut",skillchain={"Liquefaction","Impaction"}},
    [596] = {id=596,en="Pinecone Bomb",skillchain={"Liquefaction"}},
    [597] = {id=597,en="Sprout Smack",skillchain={"Reverberation"}},
    [599] = {id=599,en="Queasyshroom",skillchain={"Compression"}},
    [603] = {id=603,en="Wild Oats",skillchain={"Transfixion"}},
    [611] = {id=611,en="Disseverment",skillchain={"Distortion"}},
    [617] = {id=617,en="Vertical Cleave",skillchain={"Gravitation"}},
    [620] = {id=620,en="Battle Dance",skillchain={"Impaction"}},
    [622] = {id=622,en="Grand Slam",skillchain={"Induration"}},
    [623] = {id=623,en="Head Butt",skillchain={"Impaction"}},
    [628] = {id=628,en="Frypan",skillchain={"Impaction"}},
    [631] = {id=631,en="Hydro Shot",skillchain={"Reverberation"}},
    [638] = {id=638,en="Feather Storm",skillchain={"Transfixion"}},
    [640] = {id=640,en="Tail Slap",skillchain={"Reverberation"}},
    [641] = {id=641,en="Hysteric Barrage",skillchain={"Detonation"}},
    [643] = {id=643,en="Cannonball",skillchain={"Fusion"}},
    [650] = {id=650,en="Seedspray",skillchain={"Induration","Detonation"}},
    [652] = {id=652,en="Spiral Spin",skillchain={"Transfixion"}},
    [653] = {id=653,en="Asuran Claws",skillchain={"Impaction","Liquefaction"}},
    [654] = {id=654,en="Sub-zero Smash",skillchain={"Fragmentation"}},
    [665] = {id=665,en="Final Sting",skillchain={"Fusion"}},
    [666] = {id=666,en="Goblin Rush",skillchain={"Fusion","Impaction"}},
    [667] = {id=667,en="Vanity Dive",skillchain={"Transfixion","Scission"}},
    [669] = {id=669,en="Whirl of Rage",skillchain={"Scission","Detonation"}},
    [670] = {id=670,en="Benthic Typhoon",skillchain={"Gravitation","Transfixion"}},
    [673] = {id=673,en="Quad. Continuum",skillchain={"Distortion","Scission"}},
    [677] = {id=677,en="Empty Thrash",skillchain={"Compression","Scission"}},
    [682] = {id=682,en="Delta Thrust",skillchain={"Liquefaction","Detonation"}},
    [688] = {id=688,en="Heavy Strike",skillchain={"Fragmentation","Transfixion"}},
    [692] = {id=692,en="Sudden Lunge",skillchain={"Detonation"}},
    [693] = {id=693,en="Quadrastrike",skillchain={"Liquefaction","Scission"}},
    [697] = {id=697,en="Amorphic Spikes",skillchain={"Gravitation"}},
    [699] = {id=699,en="Barbed Crescent",skillchain={"Distortion","Liquefaction"}},
    [704] = {id=704,en="Paralyzing Triad",skillchain={"Gravitation"}},
    [706] = {id=706,en="Glutinous Dart",skillchain={"Fragmentation"}},
    [709] = {id=709,en="Thrashing Assault",skillchain={"Fusion"}},
    [714] = {id=714,en="Sinker Drill",skillchain={"Gravitation","Reverberation"}},
    [723] = {id=723,en="Saurian Slide",skillchain={"Fragmentation","Distortion"}},
    [740] = {id=740,en="Tourbillion",skillchain={"Light","Fragmentation"}},
    [742] = {id=742,en="Bilgestorm",skillchain={"Darkness","Gravitation"}},
    [743] = {id=743,en="Bloodrake",skillchain={"Darkness","Distortion"}},
    }

skills.monster = {
    [302] = {id=302,en="Wild Oats",skillchain={"Transfixion"}},
    [521] = {id=521,en="Spinning Attack",skillchain={"Liquefaction","Impaction"}},
    [584] = {id=584,en="Uppercut",skillchain={"Liquefaction","Impaction"}},
    [590] = {id=590,en="Goblin Rush",skillchain={"Fusion","Impaction"}},
    [683] = {id=683,en="Bludgeon",skillchain={"Fusion","Liquefaction"}},
    [684] = {id=684,en="Deal Out",skillchain={"Distortion"}},
    [829] = {id=829,en="Great Wheel",skillchain={"Fragmentation","Scission"}},
    [830] = {id=830,en="Light Blade",skillchain={"Fusion"}},
    [838] = {id=838,en="Howling Moon",skillchain={"Darkness","Gravitation"}},
    [839] = {id=839,en="Howling Moon",skillchain={"Darkness","Gravitation"}},
    [932] = {id=932,en="Havoc Spiral",skillchain={"Light"}},
    [938] = {id=938,en="Circle Blade",skillchain={"Reverberation","Impaction"}},
    [939] = {id=939,en="Swift Blade",skillchain={"Gravitation"}},
    [940] = {id=940,en="Rampage",skillchain={"Scission"}},
    [941] = {id=941,en="Calamity",skillchain={"Scission","Impaction"}},
    [943] = {id=943,en="Vorpal Blade",skillchain={"Scission","Impaction"}},
    [944] = {id=944,en="Spinning Scythe",skillchain={"Reverberation","Scission"}},
    [945] = {id=945,en="Guillotine",skillchain={"Induration"}},
    [946] = {id=946,en="Tachi: Yukikaze",skillchain={"Induration","Detonation"}},
    [947] = {id=947,en="Tachi: Gekko",skillchain={"Distortion","Reverberation"}},
    [948] = {id=948,en="Tachi: Kasha",skillchain={"Fusion","Compression"}},
    [951] = {id=951,en="Hurricane Wing",skillchain={"Detonation"}},
    [953] = {id=953,en="Dragon Breath",skillchain={"Fusion"}},
    [956] = {id=956,en="Hurricane Wing",skillchain={"Detonation"}},
    [968] = {id=968,en="Red Lotus Blade",skillchain={"Liquefaction","Detonation"}},
    [969] = {id=969,en="Flat Blade",skillchain={"Impaction"}},
    [970] = {id=970,en="Savage Blade",skillchain={"Fragmentation","Scission"}},
    [973] = {id=973,en="Red Lotus Blade",skillchain={"Liquefaction","Detonation"}},
    [975] = {id=975,en="Vorpal Blade",skillchain={"Scission","Impaction"}},
    [979] = {id=979,en="Power Slash",skillchain={"Transfixion"}},
    [980] = {id=980,en="Freezebite",skillchain={"Induration","Detonation"}},
    [981] = {id=981,en="Ground Strike",skillchain={"Fragmentation","Distortion"}},
    [985] = {id=985,en="Stellar Burst",skillchain={"Gravitation"}},
    [986] = {id=986,en="Vortex",skillchain={"Distortion","Reverberation"}},
    [987] = {id=987,en="Shockwave",skillchain={"Reverberation"}},
    [1027] = {id=1027,en="Combo",skillchain={"Impaction"}},
    [1030] = {id=1030,en="Backhand Blow",skillchain={"Detonation"}},
    [1031] = {id=1031,en="Spinning Attack",skillchain={"Liquefaction","Impaction"}},
    [1032] = {id=1032,en="Howling Fist",skillchain={"Transfixion","Impaction"}},
    [1033] = {id=1033,en="Dragon Kick",skillchain={"Fragmentation"}},
    [1034] = {id=1034,en="Asuran Fists",skillchain={"Gravitation","Liquefaction"}},
    [1039] = {id=1039,en="Hurricane Wing",skillchain={"Detonation"}},
    [1041] = {id=1041,en="Dragon Breath",skillchain={"Fusion"}},
    [1088] = {id=1088,en="Goblin Rush",skillchain={"Fusion","Impaction"}},
    [1188] = {id=1188,en="Final Heaven",skillchain={"Light","Fusion"}},
    [1189] = {id=1189,en="Mercy Stroke",skillchain={"Darkness","Gravitation"}},
    [1190] = {id=1190,en="Knights of Round",skillchain={"Light","Fusion"}},
    [1191] = {id=1191,en="Scourge",skillchain={"Light","Fusion"}},
    [1192] = {id=1192,en="Onslaught",skillchain={"Darkness","Gravitation"}},
    [1193] = {id=1193,en="Metatron Torment",skillchain={"Light","Fusion"}},
    [1194] = {id=1194,en="Catastrophe",skillchain={"Darkness","Gravitation"}},
    [1195] = {id=1195,en="Geirskogul",skillchain={"Light","Distortion"}},
    [1196] = {id=1196,en="Blade: Metsu",skillchain={"Darkness","Fragmentation"}},
    [1197] = {id=1197,en="Tachi: Kaiten",skillchain={"Light","Fragmentation"}},
    [1198] = {id=1198,en="Randgrith",skillchain={"Light","Fragmentation"}},
    [1199] = {id=1199,en="Gate of Tartarus",skillchain={"Darkness","Distortion"}},
    [1201] = {id=1201,en="Coronach",skillchain={"Darkness","Fragmentation"}},
    [1390] = {id=1390,en="Amatsu: Torimai",skillchain={"Transfixion","Scission"}},
    [1391] = {id=1391,en="Amatsu: Kazakiri",skillchain={"Scission","Detonation"}},
    [1392] = {id=1392,en="Amatsu: Yukiarashi",skillchain={"Induration","Detonation"}},
    [1393] = {id=1393,en="Amatsu: Tsukioboro",skillchain={"Distortion","Reverberation"}},
    [1394] = {id=1394,en="Amatsu: Hanaikusa",skillchain={"Fusion","Compression"}},
    [1395] = {id=1395,en="Amatsu: Tsukikage",skillchain={"Fragmentation","Detonation"}},
    [1444] = {id=1444,en="Vorpal Blade",skillchain={"Scission","Impaction"}},
    [1476] = {id=1476,en="Red Lotus Blade",skillchain={"Liquefaction","Detonation"}},
    [1477] = {id=1477,en="Flat Blade",skillchain={"Impaction"}},
    [1478] = {id=1478,en="Savage Blade",skillchain={"Fragmentation","Scission"}},
    [1481] = {id=1481,en="Red Lotus Blade",skillchain={"Liquefaction","Detonation"}},
    [1483] = {id=1483,en="Vorpal Blade",skillchain={"Scission","Impaction"}},
    [1489] = {id=1489,en="Nullifying Dropkick",skillchain={"Induration"}},
    [1490] = {id=1490,en="Auroral Uppercut",skillchain={"Fragmentation"}},
    [1508] = {id=1508,en="Luminous Lance",skillchain={"Light"}},
    [1509] = {id=1509,en="Rejuvenation",skillchain={"Light"}},
    [1510] = {id=1510,en="Revelation",skillchain={"Fusion"}},
    [1517] = {id=1517,en="Goblin Rush",skillchain={"Fusion","Impaction"}},
    [1520] = {id=1520,en="Howling Moon",skillchain={"Darkness","Gravitation"}},
    [1586] = {id=1586,en="Wild Oats",skillchain={"Transfixion"}},
    [1618] = {id=1618,en="Uppercut",skillchain={"Liquefaction","Impaction"}},
    [1737] = {id=1737,en="Vorpal Blade",skillchain={"Scission","Impaction"}},
    [1854] = {id=1854,en="Stellar Burst",skillchain={"Gravitation"}},
    [1914] = {id=1914,en="Great Wheel",skillchain={"Fragmentation","Scission"}},
    [1936] = {id=1936,en="Shibaraku",skillchain={"Gravitation"}},
    [1940] = {id=1940,en="Chimera Ripper",skillchain={"Detonation","Induration"}},
    [1941] = {id=1941,en="String Clipper",skillchain={"Scission"}},
    [1942] = {id=1942,en="Arcuballista",skillchain={"Liquefaction","Transfixion"}},
    [1943] = {id=1943,en="Slapstick",skillchain={"Reverberation","Impaction"}},
    [1982] = {id=1982,en="Nullifying Dropkick",skillchain={"Induration"}},
    [1983] = {id=1983,en="Auroral Uppercut",skillchain={"Fragmentation"}},
    [1998] = {id=1998,en="Hane Fubuki",skillchain={"Transfixion"}},
    [2001] = {id=2001,en="Happobarai",skillchain={"Reverberation","Impaction"}},
    [2065] = {id=2065,en="Cannibal Blade",skillchain={"Compression","Reverberation"}},
    [2066] = {id=2066,en="Daze",skillchain={"Transfixion"}},
    [2067] = {id=2067,en="Knockout",skillchain={"Detonation","Scission"}},
    [2091] = {id=2091,en="Meteoric Impact",skillchain={"Fragmentation"}},
    [2137] = {id=2137,en="Meteoric Impact",skillchain={"Fragmentation"}},
    [2140] = {id=2140,en="Peacebreaker",skillchain={"Gravitation"}},
    [2273] = {id=2273,en="Uriel Blade",skillchain={"Light","Fragmentation"}},
    [2278] = {id=2278,en="Glory Slash",skillchain={"Light","Fusion"}},
    [2299] = {id=2299,en="Bone Crusher",skillchain={"Fragmentation"}},
    [2300] = {id=2300,en="Armor Piercer",skillchain={"Gravitation"}},
    [2301] = {id=2301,en="Magic Mortar",skillchain={"Fusion","Liquefaction"}},
    [2444] = {id=2444,en="Dancer's Fury",skillchain={"Fragmentation"}},
    [2445] = {id=2445,en="Whirling Edge",skillchain={"Distortion"}},
    [2468] = {id=2468,en="King Cobra Clamp",skillchain={"Fragmentation"}},
    [2469] = {id=2469,en="Wasp Sting",skillchain={"Scission"}},
    [2470] = {id=2470,en="Dancing Edge",skillchain={"Scission","Detonation"}},
    [2588] = {id=2588,en="Debonair Rush",skillchain={"Detonation","Transfixion"}},
    [2589] = {id=2589,en="Iridal Pierce",skillchain={"Light","Fragmentation"}},
    [2590] = {id=2590,en="Lunar Revolution",skillchain={"Gravitation","Reverberation"}},
    [2594] = {id=2594,en="Quietus Sphere",skillchain={"Fragmentation"}},
    [2743] = {id=2743,en="String Shredder",skillchain={"Distortion","Scission"}},
    [2744] = {id=2744,en="Armor Shatterer",skillchain={"Fusion","Impaction"}},
    [2891] = {id=2891,en="Grapeshot",skillchain={"Transfixion","Reverberation"}},
    [2892] = {id=2892,en="Pirate Pummel",skillchain={"Fusion","Impaction"}},
    [2893] = {id=2893,en="Powder Keg",skillchain={"Fusion","Compression"}},
    [2894] = {id=2894,en="Walk the Plank",skillchain={"Fragmentation","Distortion"}},
    [2895] = {id=2895,en="Knuckle Sandwich",skillchain={"Fusion"}},
    [2896] = {id=2896,en="Imperial Authority",skillchain={"Distortion"}},
    [2897] = {id=2897,en="Sixth Element",skillchain={"Gravitation"}},
    [3161] = {id=3161,en="Camaraderie of the Crevasse",skillchain={"Detonation","Impaction"}},
    [3162] = {id=3162,en="Into the Light",skillchain={"Fragmentation","Impaction"}},
    [3163] = {id=3163,en="Arduous Decision",skillchain={"Fragmentation","Compression"}},
    [3164] = {id=3164,en="12 Blades of Remorse",skillchain={"Distortion"}},
    [3168] = {id=3168,en="Aurous Charge",skillchain={"Liquefaction","Transfixion"}},
    [3170] = {id=3170,en="Righteous Rasp",skillchain={"Fusion","Transfixion"}},
    [3171] = {id=3171,en="Starward Yowl",skillchain={"Gravitation"}},
    [3172] = {id=3172,en="Stalking Prey",skillchain={"Light"}},
    [3176] = {id=3176,en="Chant du Cygne",skillchain={"Light","Distortion"}},
    [3179] = {id=3179,en="Chant du Cygne",skillchain={"Light","Distortion"}},
    [3184] = {id=3184,en="Havoc Spiral",skillchain={"Light"}},
    [3185] = {id=3185,en="Cloudsplitter",skillchain={"Darkness","Fragmentation"}},
    [3188] = {id=3188,en="Tachi: Fudo",skillchain={"Light","Distortion"}},
    [3189] = {id=3189,en="King Cobra Clamp",skillchain={"Fragmentation"}},
    [3190] = {id=3190,en="Red Lotus Blade",skillchain={"Liquefaction","Detonation"}},
    [3192] = {id=3192,en="Vorpal Blade",skillchain={"Scission","Impaction"}},
    [3197] = {id=3197,en="Ground Strike",skillchain={"Fragmentation","Distortion"}},
    [3198] = {id=3198,en="Grapeshot",skillchain={"Transfixion","Reverberation"}},
    [3199] = {id=3199,en="Pirate Pummel",skillchain={"Fusion","Impaction"}},
    [3200] = {id=3200,en="Powder Keg",skillchain={"Fusion","Compression"}},
    [3201] = {id=3201,en="Walk the Plank",skillchain={"Fragmentation","Distortion"}},
    [3202] = {id=3202,en="Uriel Blade",skillchain={"Light","Fragmentation"}},
    [3204] = {id=3204,en="Amatsu: Tsukikage",skillchain={"Fragmentation","Detonation"}},
    [3213] = {id=3213,en="Vortex",skillchain={"Distortion","Reverberation"}},
    [3214] = {id=3214,en="Light Blade",skillchain={"Fusion"}},
    [3215] = {id=3215,en="Peacebreaker",skillchain={"Gravitation"}},
    [3216] = {id=3216,en="Red Lotus Blade",skillchain={"Liquefaction","Detonation"}},
    [3217] = {id=3217,en="Savage Blade",skillchain={"Fragmentation","Scission"}},
    [3231] = {id=3231,en="Debonair Rush",skillchain={"Detonation","Transfixion"}},
    [3232] = {id=3232,en="Iridal Pierce",skillchain={"Light","Fragmentation"}},
    [3233] = {id=3233,en="Lunar Revolution",skillchain={"Gravitation","Reverberation"}},
    [3234] = {id=3234,en="Nullifying Dropkick",skillchain={"Induration"}},
    [3235] = {id=3235,en="Auroral Uppercut",skillchain={"Fragmentation"}},
    [3236] = {id=3236,en="Knuckle Sandwich",skillchain={"Fusion"}},
    [3240] = {id=3240,en="Meteoric Impact",skillchain={"Fragmentation"}},
    [3243] = {id=3243,en="Imperial Authority",skillchain={"Distortion"}},
    [3244] = {id=3244,en="Sixth Element",skillchain={"Gravitation"}},
    [3252] = {id=3252,en="Bisection",skillchain={"Fragmentation","Scission"}},
    [3253] = {id=3253,en="Leaden Salute",skillchain={"Gravitation","Transfixion"}},
    [3254] = {id=3254,en="Akimbo Shot",skillchain={"Reverberation","Detonation"}},
    [3255] = {id=3255,en="Grisly Horizon",skillchain={"Gravitation"}},
    [3256] = {id=3256,en="Hane Fubuki",skillchain={"Transfixion"}},
    [3257] = {id=3257,en="Shibaraku",skillchain={"Gravitation"}},
    [3259] = {id=3259,en="Happobarai",skillchain={"Reverberation","Impaction"}},
    [3262] = {id=3262,en="Goblin Rush",skillchain={"Fusion","Impaction"}},
    [3283] = {id=3283,en="Iniquitous Stab",skillchain={"Gravitation"}},
    [3284] = {id=3284,en="Shockstorm Edge",skillchain={"Detonation","Impaction"}},
    [3286] = {id=3286,en="Lock and Load",skillchain={"Fusion"}},
    [3310] = {id=3310,en="Dancer's Fury",skillchain={"Fragmentation"}},
    [3311] = {id=3311,en="Whirling Edge",skillchain={"Distortion"}},
    [3314] = {id=3314,en="True Strike",skillchain={"Detonation","Impaction"}},
    [3315] = {id=3315,en="Hexa Strike",skillchain={"Fusion"}},
    [3322] = {id=3322,en="Critical Mass",skillchain={"Fusion","Impaction"}},
    [3323] = {id=3323,en="Fiery Tailings",skillchain={"Fragmentation"}},
    [3336] = {id=3336,en="Howling Moon",skillchain={"Darkness","Gravitation"}},
    [3337] = {id=3337,en="Lunar Bay",skillchain={"Gravitation","Compression"}},
    [3351] = {id=3351,en="Wild Oats",skillchain={"Transfixion"}},
    [3356] = {id=3356,en="Uppercut",skillchain={"Liquefaction","Impaction"}},
    [3381] = {id=3381,en="Frenzied Thrust",skillchain={"Fragmentation"}},
    [3382] = {id=3382,en="Sinner's Cross",skillchain={"Gravitation"}},
    [3383] = {id=3383,en="Open Coffin",skillchain={"Fusion"}},
    [3411] = {id=3411,en="Power Slash",skillchain={"Transfixion"}},
    [3412] = {id=3412,en="Freezebite",skillchain={"Induration","Detonation"}},
    [3413] = {id=3413,en="Combo",skillchain={"Impaction"}},
    [3415] = {id=3415,en="Howling Fist",skillchain={"Transfixion","Impaction"}},
    [3416] = {id=3416,en="Dragon Kick",skillchain={"Fragmentation"}},
    [3417] = {id=3417,en="Asuran Fists",skillchain={"Gravitation","Liquefaction"}},
    [3418] = {id=3418,en="Amatsu: Torimai",skillchain={"Transfixion","Scission"}},
    [3419] = {id=3419,en="Amatsu: Kazakiri",skillchain={"Scission","Detonation"}},
    [3420] = {id=3420,en="Amatsu: Yukiarashi",skillchain={"Induration","Detonation"}},
    [3421] = {id=3421,en="Amatsu: Tsukioboro",skillchain={"Distortion","Reverberation"}},
    [3422] = {id=3422,en="Amatsu: Hanaikusa",skillchain={"Fusion","Compression"}},
    [3423] = {id=3423,en="Wasp Sting",skillchain={"Scission"}},
    [3424] = {id=3424,en="Dancing Edge",skillchain={"Scission","Detonation"}},
    [3425] = {id=3425,en="Flat Blade",skillchain={"Impaction"}},
    [3431] = {id=3431,en="Fast Blade",skillchain={"Scission"}},
    [3432] = {id=3432,en="Savage Blade",skillchain={"Fragmentation","Scission"}},
    [3434] = {id=3434,en="Tachi: Kamai",skillchain={"Detonation"}},
    [3436] = {id=3436,en="Tachi: Goten",skillchain={"Transfixion","Impaction"}},
    [3437] = {id=3437,en="Tachi: Kasha",skillchain={"Fusion","Compression"}},
    [3438] = {id=3438,en="Dragon Breath",skillchain={"Fusion"}},
    [3439] = {id=3439,en="Hurricane Wing",skillchain={"Detonation"}},
    [3445] = {id=3445,en="Merciless Strike",skillchain={"Impaction"}},
    [3448] = {id=3448,en="Uppercut",skillchain={"Liquefaction","Impaction"}},
    [3454] = {id=3454,en="Coming Up Roses",skillchain={"Fragmentation"}},
    [3468] = {id=3468,en="Binding Microtube",skillchain={"Distortion"}},
    [3469] = {id=3469,en="Twirling Dervish",skillchain={"Fusion"}},
    [3470] = {id=3470,en="Great Wheel",skillchain={"Fragmentation","Scission"}},
    [3471] = {id=3471,en="Light Blade",skillchain={"Fusion"}},
    [3472] = {id=3472,en="Vortex",skillchain={"Distortion","Reverberation"}},
    [3473] = {id=3473,en="Stellar Burst",skillchain={"Gravitation"}},
    [3487] = {id=3487,en="Sidewinder",skillchain={"Reverberation","Transfixion","Detonation"}},
    [3488] = {id=3488,en="Arching Arrow",skillchain={"Fusion"}},
    [3489] = {id=3489,en="Stellar Arrow",skillchain={"Darkness","Gravitation"}},
    [3490] = {id=3490,en="Lux Arrow",skillchain={"Light","Fusion"}},
    [3491] = {id=3491,en="Grapeshot",skillchain={"Transfixion","Reverberation"}},
    [3492] = {id=3492,en="Pirate Pummel",skillchain={"Fusion","Impaction"}},
    [3493] = {id=3493,en="Powder Keg",skillchain={"Fusion","Compression"}},
    [3494] = {id=3494,en="Walk the Plank",skillchain={"Fragmentation","Distortion"}},
    [3495] = {id=3495,en="Ground Strike",skillchain={"Fragmentation","Distortion"}},
    [3496] = {id=3496,en="Hollow Smite",skillchain={"Light","Fragmentation"}},
    [3497] = {id=3497,en="Sarva's Storm",skillchain={"Darkness","Distortion"}},
    [3498] = {id=3498,en="Sarva's Storm",skillchain={"Darkness","Distortion"}},
    [3499] = {id=3499,en="Soturi's Fury",skillchain={"Light","Fragmentation"}},
    [3500] = {id=3500,en="Celidon's Torment",skillchain={"Light","Fragmentation"}},
    [3501] = {id=3501,en="Tachi: Mudo",skillchain={"Light","Distortion"}},
    [3503] = {id=3503,en="Justicebreaker",skillchain={"Darkness"}},
    [3537] = {id=3537,en="Quietus Sphere",skillchain={"Fragmentation"}},
    [3538] = {id=3538,en="Null Blast",skillchain={"Fusion"}},
    [3543] = {id=3543,en="Knuckle Sandwich",skillchain={"Fusion"}},
    [3544] = {id=3544,en="Whirling Edge",skillchain={"Distortion"}},
    [3551] = {id=3551,en="Lunar Bay",skillchain={"Gravitation","Compression"}},
    [3556] = {id=3556,en="Amatsu: Fuga",skillchain={"Impaction"}},
    [3557] = {id=3557,en="Amatsu: Kyori",skillchain={"Induration"}},
    [3558] = {id=3558,en="Amatsu: Hanadoki",skillchain={"Reverberation","Scission"}},
    [3559] = {id=3559,en="Amatsu: Choun",skillchain={"Liquefaction"}},
    [3560] = {id=3560,en="Amatsu: Gachirin",skillchain={"Light","Fragmentation"}},
    [3561] = {id=3561,en="Amatsu: Suien",skillchain={"Fusion","Liquefaction"}},
    [3580] = {id=3580,en="Harmonic Displacement",skillchain={"Fusion","Reverberation"}},
    [3581] = {id=3581,en="Sight Unseen",skillchain={"Fragmentation"}},
    [3582] = {id=3582,en="Darkest Hour",skillchain={"Gravitation"}},
    [3585] = {id=3585,en="Naakual's Vengeance",skillchain={"Induration"}},
    [3591] = {id=3591,en="Tartaric Sigil",skillchain={"Compression","Scission"}},
    [3592] = {id=3592,en="Null Field",skillchain={"Fusion","Transfixion"}},
    [3593] = {id=3593,en="Alabaster Burst",skillchain={"Distortion","Detonation"}},
    [3594] = {id=3594,en="Noble Frenzy",skillchain={"Gravitation"}},
    [3595] = {id=3595,en="Fulminous Fury",skillchain={"Fragmentation"}},
    [3596] = {id=3596,en="No Quarter",skillchain={"Light","Distortion"}},
    [3611] = {id=3611,en="Inexorable Strike",skillchain={"Fusion"}},
    [3621] = {id=3621,en="Luminous Lance",skillchain={"Light"}},
    [3622] = {id=3622,en="Rejuvenation",skillchain={"Light"}},
    [3623] = {id=3623,en="Revelation",skillchain={"Fusion"}},
    [3632] = {id=3632,en="Frenzied Thrust",skillchain={"Fragmentation"}},
    [3633] = {id=3633,en="Sinner's Cross",skillchain={"Gravitation"}},
    [3634] = {id=3634,en="Open Coffin",skillchain={"Fusion"}},
    [3645] = {id=3645,en="Inexorable Strike",skillchain={"Fusion"}},
    [3647] = {id=3647,en="Merciless Strike",skillchain={"Impaction"}},
    [3653] = {id=3653,en="Tartaric Sigil",skillchain={"Compression","Scission"}},
    [3654] = {id=3654,en="Null Field",skillchain={"Fusion","Transfixion"}},
    [3655] = {id=3655,en="Alabaster Burst",skillchain={"Distortion","Detonation"}},
    [3656] = {id=3656,en="Noble Frenzy",skillchain={"Gravitation"}},
    [3657] = {id=3657,en="Fulminous Fury",skillchain={"Fragmentation"}},
    [3658] = {id=3658,en="No Quarter",skillchain={"Light","Distortion"}},
    [3677] = {id=3677,en="Camaraderie of the Crevasse",skillchain={"Detonation","Impaction"}},
    [3678] = {id=3678,en="Into the Light",skillchain={"Fragmentation","Impaction"}},
    [3679] = {id=3679,en="Arduous Decision",skillchain={"Fragmentation","Compression"}},
    [3680] = {id=3680,en="12 Blades of Remorse",skillchain={"Distortion"}},
    [3684] = {id=3684,en="Aurous Charge",skillchain={"Liquefaction","Transfixion"}},
    [3686] = {id=3686,en="Righteous Rasp",skillchain={"Fusion","Transfixion"}},
    [3687] = {id=3687,en="Starward Yowl",skillchain={"Gravitation"}},
    [3688] = {id=3688,en="Stalking Prey",skillchain={"Light"}},
    [3691] = {id=3691,en="Bludgeon",skillchain={"Fusion","Liquefaction"}},
    [3692] = {id=3692,en="Deal Out",skillchain={"Distortion"}},
    [3700] = {id=3700,en="Harmonic Displacement",skillchain={"Fusion","Reverberation"}},
    [3701] = {id=3701,en="Sight Unseen",skillchain={"Fragmentation"}},
    [3702] = {id=3702,en="Darkest Hour",skillchain={"Gravitation"}},
    [3705] = {id=3705,en="Naakual's Vengeance",skillchain={"Induration"}},
    [3707] = {id=3707,en="Circle Blade",skillchain={"Reverberation","Impaction"}},
    [3708] = {id=3708,en="Swift Blade",skillchain={"Gravitation"}},
    [3709] = {id=3709,en="Chant du Cygne",skillchain={"Light","Distortion"}},
    [3711] = {id=3711,en="Vorpal Blade",skillchain={"Scission","Impaction"}},
    [3713] = {id=3713,en="Chant du Cygne",skillchain={"Light","Distortion"}},
    [3715] = {id=3715,en="Rampage",skillchain={"Scission"}},
    [3716] = {id=3716,en="Calamity",skillchain={"Scission","Impaction"}},
    [3717] = {id=3717,en="Havoc Spiral",skillchain={"Light"}},
    [3718] = {id=3718,en="Cloudsplitter",skillchain={"Darkness","Fragmentation"}},
    [3719] = {id=3719,en="Spinning Scythe",skillchain={"Reverberation","Scission"}},
    [3721] = {id=3721,en="Guillotine",skillchain={"Induration"}},
    [3722] = {id=3722,en="Tachi: Yukikaze",skillchain={"Induration","Detonation"}},
    [3723] = {id=3723,en="Tachi: Gekko",skillchain={"Distortion","Reverberation"}},
    [3725] = {id=3725,en="Tachi: Kasha",skillchain={"Fusion","Compression"}},
    [3726] = {id=3726,en="Tachi: Fudo",skillchain={"Light","Distortion"}},
    [3732] = {id=3732,en="Amatsu: Fuga",skillchain={"Impaction"}},
    [3733] = {id=3733,en="Amatsu: Kyori",skillchain={"Induration"}},
    [3734] = {id=3734,en="Amatsu: Hanadoki",skillchain={"Reverberation","Scission"}},
    [3735] = {id=3735,en="Amatsu: Choun",skillchain={"Liquefaction"}},
    [3736] = {id=3736,en="Amatsu: Gachirin",skillchain={"Light","Fragmentation"}},
    [3737] = {id=3737,en="Amatsu: Suien",skillchain={"Fusion","Liquefaction"}},
    [3740] = {id=3740,en="Final Exam",skillchain={"Light","Fusion"}},
    [3741] = {id=3741,en="Doctor's Orders",skillchain={"Darkness","Gravitation"}},
    [3742] = {id=3742,en="Empirical Research",skillchain={"Fragmentation","Transfixion"}},
    [3743] = {id=3743,en="Lesson in Pain",skillchain={"Distortion","Scission"}},
    [3840] = {id=3840,en="Foot Kick",skillchain={"Reverberation"}},
    [3842] = {id=3842,en="Whirl Claws",skillchain={"Impaction"}},
    [3843] = {id=3843,en="Head Butt",skillchain={"Detonation"}},
    [3845] = {id=3845,en="Wild Oats",skillchain={"Transfixion"}},
    [3846] = {id=3846,en="Leaf Dagger",skillchain={"Scission"}},
    [3849] = {id=3849,en="Razor Fang",skillchain={"Impaction"}},
    [3850] = {id=3850,en="Claw Cyclone",skillchain={"Scission"}},
    [3851] = {id=3851,en="Tail Blow",skillchain={"Impaction"}},
    [3853] = {id=3853,en="Blockhead",skillchain={"Reverberation"}},
    [3854] = {id=3854,en="Brain Crush",skillchain={"Liquefaction"}},
    [3857] = {id=3857,en="Lamb Chop",skillchain={"Impaction"}},
    [3859] = {id=3859,en="Sheep Charge",skillchain={"Reverberation"}},
    [3863] = {id=3863,en="Big Scissors",skillchain={"Scission"}},
    [3866] = {id=3866,en="Needleshot",skillchain={"Transfixion"}},
    [3867] = {id=3867,en="??? Needles",skillchain={"Darkness","Fragmentation"}},
    [3868] = {id=3868,en="Frogkick",skillchain={"Compression"}},
    [3875] = {id=3875,en="Power Attack",skillchain={"Reverberation"}},
    [3877] = {id=3877,en="Rhino Attack",skillchain={"Detonation"}},
    [3885] = {id=3885,en="Mandibular Bite",skillchain={"Detonation"}},
    [3891] = {id=3891,en="Nimble Snap",skillchain={"Impaction"}},
    [3892] = {id=3892,en="Cyclotail",skillchain={"Impaction"}},
    [3894] = {id=3894,en="Double Claw",skillchain={"Liquefaction"}},
    [3895] = {id=3895,en="Grapple",skillchain={"Reverberation"}},
    [3897] = {id=3897,en="Spinning Top",skillchain={"Impaction"}},
    [3900] = {id=3900,en="Suction",skillchain={"Compression"}},
    [3904] = {id=3904,en="Sudden Lunge",skillchain={"Impaction"}},
    [3905] = {id=3905,en="Spiral Spin",skillchain={"Scission"}},
    [3909] = {id=3909,en="Scythe Tail",skillchain={"Liquefaction"}},
    [3910] = {id=3910,en="Ripper Fang",skillchain={"Induration"}},
    [3911] = {id=3911,en="Chomp Rush",skillchain={"Darkness","Gravitation"}},
    [3915] = {id=3915,en="Back Heel",skillchain={"Reverberation"}},
    [3919] = {id=3919,en="Tortoise Stomp",skillchain={"Liquefaction"}},
    [3922] = {id=3922,en="Wing Slap",skillchain={"Gravitation","Liquefaction"}},
    [3923] = {id=3923,en="Beak Lunge",skillchain={"Scission"}},
    [3925] = {id=3925,en="Recoil Dive",skillchain={"Transfixion"}},
    [3927] = {id=3927,en="Sensilla Blades",skillchain={"Scission"}},
    [3928] = {id=3928,en="Tegmina Buffet",skillchain={"Distortion","Detonation"}},
    [3930] = {id=3930,en="Swooping Frenzy",skillchain={"Fusion","Reverberation"}},
    [3931] = {id=3931,en="Sweeping Gouge",skillchain={"Induration"}},
    [3933] = {id=3933,en="Pentapeck",skillchain={"Light","Distortion"}},
    [3934] = {id=3934,en="Tickling Tendrils",skillchain={"Impaction"}},
    [3938] = {id=3938,en="Somersault",skillchain={"Compression"}},
    [3941] = {id=3941,en="Pecking Flurry",skillchain={"Transfixion"}},
    [3942] = {id=3942,en="Sickle Slash",skillchain={"Transfixion"}},
    }

skills.spells = {
    [144] = {id=144,en="Fire",skillchain={"Liquefaction"},element=0},
    [145] = {id=145,en="Fire II",skillchain={"Liquefaction"},element=0},
    [146] = {id=146,en="Fire III",skillchain={"Liquefaction"},element=0},
    [147] = {id=147,en="Fire IV",skillchain={"Liquefaction"},element=0},
    [148] = {id=148,en="Fire V",skillchain={"Liquefaction"},element=0},
    [149] = {id=149,en="Blizzard",skillchain={"Induration"},element=1},
    [150] = {id=150,en="Blizzard II",skillchain={"Induration"},element=1},
    [151] = {id=151,en="Blizzard III",skillchain={"Induration"},element=1},
    [152] = {id=152,en="Blizzard IV",skillchain={"Induration"},element=1},
    [153] = {id=153,en="Blizzard V",skillchain={"Induration"},element=1},
    [154] = {id=154,en="Aero",skillchain={"Detonation"},element=2},
    [155] = {id=155,en="Aero II",skillchain={"Detonation"},element=2},
    [156] = {id=156,en="Aero III",skillchain={"Detonation"},element=2},
    [157] = {id=157,en="Aero IV",skillchain={"Detonation"},element=2},
    [158] = {id=158,en="Aero V",skillchain={"Detonation"},element=2},
    [159] = {id=159,en="Stone",skillchain={"Scission"},element=3},
    [160] = {id=160,en="Stone II",skillchain={"Scission"},element=3},
    [161] = {id=161,en="Stone III",skillchain={"Scission"},element=3},
    [162] = {id=162,en="Stone IV",skillchain={"Scission"},element=3},
    [163] = {id=163,en="Stone V",skillchain={"Scission"},element=3},
    [164] = {id=164,en="Thunder",skillchain={"Impaction"},element=4},
    [165] = {id=165,en="Thunder II",skillchain={"Impaction"},element=4},
    [166] = {id=166,en="Thunder III",skillchain={"Impaction"},element=4},
    [167] = {id=167,en="Thunder IV",skillchain={"Impaction"},element=4},
    [168] = {id=168,en="Thunder V",skillchain={"Impaction"},element=4},
    [169] = {id=169,en="Water",skillchain={"Reverberation"},element=5},
    [170] = {id=170,en="Water II",skillchain={"Reverberation"},element=5},
    [171] = {id=171,en="Water III",skillchain={"Reverberation"},element=5},
    [172] = {id=172,en="Water IV",skillchain={"Reverberation"},element=5},
    [173] = {id=173,en="Water V",skillchain={"Reverberation"},element=5},
    [174] = {id=174,en="Firaga",skillchain={"Liquefaction"},element=0},
    [179] = {id=179,en="Blizzaga",skillchain={"Induration"},element=1},
    [184] = {id=184,en="Aeroga",skillchain={"Detonation"},element=2},
    [185] = {id=185,en="Aeroga II",skillchain={"Detonation"},element=2},
    [189] = {id=189,en="Stonega",skillchain={"Scission"},element=3},
    [190] = {id=190,en="Stonega II",skillchain={"Scission"},element=3},
    [194] = {id=194,en="Thundaga",skillchain={"Impaction"},element=4},
    [199] = {id=199,en="Waterga",skillchain={"Reverberation"},element=5},
    [200] = {id=200,en="Waterga II",skillchain={"Reverberation"},element=5},
    [235] = {id=235,en="Burn",skillchain={"Liquefaction"},element=0},
    [236] = {id=236,en="Frost",skillchain={"Induration"},element=1},
    [237] = {id=237,en="Choke",skillchain={"Detonation"},element=2},
    [238] = {id=238,en="Rasp",skillchain={"Scission"},element=3},
    [239] = {id=239,en="Shock",skillchain={"Impaction"},element=4},
    [240] = {id=240,en="Drown",skillchain={"Reverberation"},element=5},
    [278] = {id=278,en="Geohelix",skillchain={"Scission"},element=3},
    [279] = {id=279,en="Hydrohelix",skillchain={"Reverberation"},element=5},
    [280] = {id=280,en="Anemohelix",skillchain={"Detonation"},element=2},
    [281] = {id=281,en="Pyrohelix",skillchain={"Liquefaction"},element=0},
    [282] = {id=282,en="Cryohelix",skillchain={"Induration"},element=1},
    [283] = {id=283,en="Ionohelix",skillchain={"Impaction"},element=4},
    [284] = {id=284,en="Noctohelix",skillchain={"Compression"},element=7},
    [285] = {id=285,en="Luminohelix",skillchain={"Transfixion"},element=6},
    [503] = {id=503,en="Impact",skillchain={"Compression"},element=7},
    [885] = {id=885,en="Geohelix II",skillchain={"Scission"},element=3},
    [886] = {id=886,en="Hydrohelix II",skillchain={"Reverberation"},element=5},
    [887] = {id=887,en="Anemohelix II",skillchain={"Detonation"},element=2},
    [888] = {id=888,en="Pyrohelix II",skillchain={"Liquefaction"},element=0},
    [889] = {id=889,en="Cryohelix II",skillchain={"Induration"},element=1},
    [890] = {id=890,en="Ionohelix II",skillchain={"Impaction"},element=4},
    [891] = {id=891,en="Noctohelix II",skillchain={"Compression"},element=7},
    [892] = {id=892,en="Luminohelix II",skillchain={"Transfixion"},element=6},
    }

skills.aeonic = {
    [22117] = 203,
    [20977] = 141,
    [20890] = 109,
    [20594] = 224,
    [21485] = 221,
    [21082] = 174,
    [20695] = 226,
    [21694] = 60,
    [21753] = 77,
    [21147] = 191,
    [20515] = 15,
    [20935] = 125,
    [21025] = 157,
    [20843] = 93,
    }

return skills
